{{- if and .Values.secretEnv.create (not .Values.existingSecretEnv.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "farmora-ai.secretName" . }}
  labels:
    {{- include "farmora-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
